apiVersion: v1
kind: Service
metadata:
  name: live-service
spec:
  type: NodePort
  selector:
    app: live
  ports:
  - protocol: TCP
    name: stream
    port: 1935
    targetPort: 1935
  - protocol: TCP
    name: chunks
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-deployment
  labels:
    app: live
spec:
  replicas: 2
  selector:
    matchLabels:
      app: live
  template:
    metadata:
      labels:
        app: live
    spec:
      containers:
      - name: live
        image: oven:v4
        imagePullPolicy: Never
        ports:
        - containerPort: 1935
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred2

